// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DueDateCalculation string

const (
	DueDateCalculationFromOriginal   DueDateCalculation = "from_original"
	DueDateCalculationFromCompletion DueDateCalculation = "from_completion"
)

func (e *DueDateCalculation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DueDateCalculation(s)
	case string:
		*e = DueDateCalculation(s)
	default:
		return fmt.Errorf("unsupported scan type for DueDateCalculation: %T", src)
	}
	return nil
}

type NullDueDateCalculation struct {
	DueDateCalculation DueDateCalculation `json:"due_date_calculation"`
	Valid              bool               `json:"valid"` // Valid is true if DueDateCalculation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDueDateCalculation) Scan(value interface{}) error {
	if value == nil {
		ns.DueDateCalculation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DueDateCalculation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDueDateCalculation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DueDateCalculation), nil
}

type RecurrencePattern string

const (
	RecurrencePatternNone    RecurrencePattern = "none"
	RecurrencePatternDaily   RecurrencePattern = "daily"
	RecurrencePatternWeekly  RecurrencePattern = "weekly"
	RecurrencePatternMonthly RecurrencePattern = "monthly"
)

func (e *RecurrencePattern) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecurrencePattern(s)
	case string:
		*e = RecurrencePattern(s)
	default:
		return fmt.Errorf("unsupported scan type for RecurrencePattern: %T", src)
	}
	return nil
}

type NullRecurrencePattern struct {
	RecurrencePattern RecurrencePattern `json:"recurrence_pattern"`
	Valid             bool              `json:"valid"` // Valid is true if RecurrencePattern is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecurrencePattern) Scan(value interface{}) error {
	if value == nil {
		ns.RecurrencePattern, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecurrencePattern.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecurrencePattern) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecurrencePattern), nil
}

type TaskEffort string

const (
	TaskEffortSmall  TaskEffort = "small"
	TaskEffortMedium TaskEffort = "medium"
	TaskEffortLarge  TaskEffort = "large"
	TaskEffortXlarge TaskEffort = "xlarge"
)

func (e *TaskEffort) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskEffort(s)
	case string:
		*e = TaskEffort(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskEffort: %T", src)
	}
	return nil
}

type NullTaskEffort struct {
	TaskEffort TaskEffort `json:"task_effort"`
	Valid      bool       `json:"valid"` // Valid is true if TaskEffort is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskEffort) Scan(value interface{}) error {
	if value == nil {
		ns.TaskEffort, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskEffort.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskEffort) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskEffort), nil
}

type TaskHistoryEventType string

const (
	TaskHistoryEventTypeCreated       TaskHistoryEventType = "created"
	TaskHistoryEventTypeUpdated       TaskHistoryEventType = "updated"
	TaskHistoryEventTypeBumped        TaskHistoryEventType = "bumped"
	TaskHistoryEventTypeCompleted     TaskHistoryEventType = "completed"
	TaskHistoryEventTypeDeleted       TaskHistoryEventType = "deleted"
	TaskHistoryEventTypeStatusChanged TaskHistoryEventType = "status_changed"
)

func (e *TaskHistoryEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskHistoryEventType(s)
	case string:
		*e = TaskHistoryEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskHistoryEventType: %T", src)
	}
	return nil
}

type NullTaskHistoryEventType struct {
	TaskHistoryEventType TaskHistoryEventType `json:"task_history_event_type"`
	Valid                bool                 `json:"valid"` // Valid is true if TaskHistoryEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskHistoryEventType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskHistoryEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskHistoryEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskHistoryEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskHistoryEventType), nil
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type CategoryPreference struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Category           string             `json:"category"`
	DueDateCalculation DueDateCalculation `json:"due_date_calculation"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Task struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Title           string             `json:"title"`
	Description     *string            `json:"description"`
	Status          TaskStatus         `json:"status"`
	UserPriority    int32              `json:"user_priority"`
	DueDate         pgtype.Timestamptz `json:"due_date"`
	EstimatedEffort NullTaskEffort     `json:"estimated_effort"`
	Category        *string            `json:"category"`
	Context         *string            `json:"context"`
	RelatedPeople   []string           `json:"related_people"`
	PriorityScore   int32              `json:"priority_score"`
	BumpCount       int32              `json:"bump_count"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	SeriesID        pgtype.UUID        `json:"series_id"`
	ParentTaskID    pgtype.UUID        `json:"parent_task_id"`
}

type TaskDependency struct {
	TaskID      pgtype.UUID        `json:"task_id"`
	BlockedByID pgtype.UUID        `json:"blocked_by_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TaskHistory struct {
	ID        pgtype.UUID          `json:"id"`
	UserID    pgtype.UUID          `json:"user_id"`
	TaskID    pgtype.UUID          `json:"task_id"`
	EventType TaskHistoryEventType `json:"event_type"`
	OldValue  *string              `json:"old_value"`
	NewValue  *string              `json:"new_value"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

type TaskSeries struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	OriginalTaskID     pgtype.UUID        `json:"original_task_id"`
	Pattern            RecurrencePattern  `json:"pattern"`
	IntervalValue      int32              `json:"interval_value"`
	EndDate            pgtype.Timestamptz `json:"end_date"`
	DueDateCalculation DueDateCalculation `json:"due_date_calculation"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserPreference struct {
	UserID                    pgtype.UUID        `json:"user_id"`
	DefaultDueDateCalculation DueDateCalculation `json:"default_due_date_calculation"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}
