// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskEffort string

const (
	TaskEffortSmall  TaskEffort = "small"
	TaskEffortMedium TaskEffort = "medium"
	TaskEffortLarge  TaskEffort = "large"
	TaskEffortXlarge TaskEffort = "xlarge"
)

func (e *TaskEffort) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskEffort(s)
	case string:
		*e = TaskEffort(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskEffort: %T", src)
	}
	return nil
}

type NullTaskEffort struct {
	TaskEffort TaskEffort `json:"task_effort"`
	Valid      bool       `json:"valid"` // Valid is true if TaskEffort is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskEffort) Scan(value interface{}) error {
	if value == nil {
		ns.TaskEffort, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskEffort.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskEffort) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskEffort), nil
}

type TaskHistoryEventType string

const (
	TaskHistoryEventTypeCreated       TaskHistoryEventType = "created"
	TaskHistoryEventTypeUpdated       TaskHistoryEventType = "updated"
	TaskHistoryEventTypeBumped        TaskHistoryEventType = "bumped"
	TaskHistoryEventTypeCompleted     TaskHistoryEventType = "completed"
	TaskHistoryEventTypeDeleted       TaskHistoryEventType = "deleted"
	TaskHistoryEventTypeStatusChanged TaskHistoryEventType = "status_changed"
)

func (e *TaskHistoryEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskHistoryEventType(s)
	case string:
		*e = TaskHistoryEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskHistoryEventType: %T", src)
	}
	return nil
}

type NullTaskHistoryEventType struct {
	TaskHistoryEventType TaskHistoryEventType `json:"task_history_event_type"`
	Valid                bool                 `json:"valid"` // Valid is true if TaskHistoryEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskHistoryEventType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskHistoryEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskHistoryEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskHistoryEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskHistoryEventType), nil
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Task struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Title           string             `json:"title"`
	Description     *string            `json:"description"`
	Status          TaskStatus         `json:"status"`
	UserPriority    int32              `json:"user_priority"`
	DueDate         pgtype.Timestamptz `json:"due_date"`
	EstimatedEffort NullTaskEffort     `json:"estimated_effort"`
	Category        *string            `json:"category"`
	Context         *string            `json:"context"`
	RelatedPeople   []string           `json:"related_people"`
	PriorityScore   int32              `json:"priority_score"`
	BumpCount       int32              `json:"bump_count"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type TaskHistory struct {
	ID        pgtype.UUID          `json:"id"`
	UserID    pgtype.UUID          `json:"user_id"`
	TaskID    pgtype.UUID          `json:"task_id"`
	EventType TaskHistoryEventType `json:"event_type"`
	OldValue  *string              `json:"old_value"`
	NewValue  *string              `json:"new_value"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
