// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskHistory = `-- name: CreateTaskHistory :exec

INSERT INTO task_history (id, user_id, task_id, event_type, old_value, new_value, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTaskHistoryParams struct {
	ID        pgtype.UUID          `json:"id"`
	UserID    pgtype.UUID          `json:"user_id"`
	TaskID    pgtype.UUID          `json:"task_id"`
	EventType TaskHistoryEventType `json:"event_type"`
	OldValue  *string              `json:"old_value"`
	NewValue  *string              `json:"new_value"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

// Task History queries for sqlc code generation
func (q *Queries) CreateTaskHistory(ctx context.Context, arg CreateTaskHistoryParams) error {
	_, err := q.db.Exec(ctx, createTaskHistory,
		arg.ID,
		arg.UserID,
		arg.TaskID,
		arg.EventType,
		arg.OldValue,
		arg.NewValue,
		arg.CreatedAt,
	)
	return err
}

const getTaskHistoryByTaskID = `-- name: GetTaskHistoryByTaskID :many
SELECT id, user_id, task_id, event_type, old_value, new_value, created_at
FROM task_history
WHERE task_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTaskHistoryByTaskID(ctx context.Context, taskID pgtype.UUID) ([]TaskHistory, error) {
	rows, err := q.db.Query(ctx, getTaskHistoryByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskHistory{}
	for rows.Next() {
		var i TaskHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.EventType,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
